# Generated by Django 4.2.17 on 2026-07-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routing", "0004_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="email",
            field=models.EmailField(default="temp@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userotp",
            name="purpose",
            field=models.CharField(
                choices=[("signup", "signup"), ("reset", "reset")],
                default="signup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
