# Generated by Django 5.0.6 on 2026-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_lat", models.FloatField()),
                ("src_lon", models.FloatField()),
                ("dst_lat", models.FloatField()),
                ("dst_lon", models.FloatField()),
                ("src_node", models.BigIntegerField()),
                ("dst_node", models.BigIntegerField()),
                ("path_distance_m", models.FloatField(help_text="metres")),
                ("path_distance_km", models.FloatField(help_text="kilometres")),
                ("node_count", models.IntegerField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Route Log",
                "ordering": ["-computed_at"],
            },
        ),
    ]
