# Generated by Django 4.2.29 on 2026-04-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routing", "0002_alter_routelog_options_routelog_dst_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routelog",
            name="path_coords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
